# These are supported funding model platforms

github: [AutuanLiu]
patreon: autuanliu
open_collective: AutuanLiu
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/kalman-estimation
custom: # Replace with a single custom sponsorship URL
